---
- name: Build fabric config
  hosts: FABRIC
  tasks:
    - name: Generate AVD structured configs and fabric documentation
      import_role:
        name: arista.avd.eos_designs
    - name: Generate Device Configurations and Documentation
      import_role:
        name: arista.avd.eos_cli_config_gen
