---
- name: Add VLANs
  hosts: Leafs_DC1
  vars:
    vlans: [10, 20, 30, 40]
  tasks:
    - name: Add a single VLANs
      arista.eos.eos_vlans:
        config:
        - vlan_id: "{{ item }}"
          state: active
        state: merged
      loop: "{{ vlans }}"