---
- name: Add user
  hosts: DC1
  tasks:
    - name: Add a user
      arista.eos.eos_user:
        name: automator
        nopassword: true
        privilege: 15
        role: network-admin
    - name: Add SSH Key to user
      arista.eos.eos_user:
        name: automator
        sshkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJP8mEf82JRslo9rwNVa7ivlUwHUAYcILixJWHD0ojybT112RYckgdemYpw1PXi/pAL7/5twL+OSWfwSvy/kcTTdoRwPggsrKzyyR1uCb+UyqRCsPo41hfeD+HOqsDO98ithPO5q4mOohNddWaNKXMTXB4vqOOTqNxq79cGWLWlbCM2vKRlGClpFAZ0YkF0bMBh6fPa74EuxcdYjGqijPFnGdlOOTPwhrCrLjjXhSyfwcebYNB1EWsf+IldXGvSS6ngLZSYiZzS3oq28VQy3TlJ3pbXTNPLOwfFJitn2iH/Yd6UZ1sb60zqtbvUlHSDTHFy4FnItPE+4Kp6LUUVKdZ arista@june2023l5-spare-1-c22abf98"